### ISSUE TITLE
Muxing same subs over and over

### ISSUE THREAD

**Issue by Barbait** [Serede/mkvtoolnix-batch#3]
Hi, i've got a folder with a season of a tv series. It contains 9 episodes and 9 .srt files.
I've modified the script at line 9:
From this:
`for %%f in (*.mkv) do %mkvmerge% @options.json -o "mkvmerge_out/%%f" "%%f"`
To this:
`for %%f in (*.mp4) do %mkvmerge% @options.json -o "mkvmerge_out/%%f.mkv" "%%f"`

So the batch grabs the mp4 files and outputs mkv files with subs.

It can mux all episodes but the problem is that it uses only the subtitles i've used to generate the option.json. If i use subtitles of episode 1 it puts at every episode those subs.

**Comment by Serede** [comment]
Hello @Barbait. The case you are posing was already commented in issue #1. Please use the procedure I described there and specify the sub files in the BAT script rather than the JSON file.
